import { Dimensions, StyleSheet } from 'react-native';

// Get screen dimensions for grid layout
const { width: screenWidth } = Dimensions.get('window');
const cardWidth = (screenWidth - 60) / 2; // 2 columns with padding
const cardHeight = cardWidth * 1.77; // 9:16 aspect ratio

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0b0b0c',
  },
  webview: {
    flex: 1,
    backgroundColor: '#000',
  },
  menuContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  titleRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    paddingTop: 60,
    paddingBottom: 8,
    position: 'relative',
  },
  title: {
    color: '#e8e8ea',
    fontSize: 28,
    fontWeight: '700',
    textAlign: 'center',
  },
  filterButton: {
    backgroundColor: 'rgba(0, 123, 255, 0.15)',
    borderRadius: 12,
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0, 123, 255, 0.4)',
    shadowColor: '#007bff',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
    position: 'absolute',
    right: 0,
    top: 55,
  },
  filterButtonText: {
    color: '#007bff',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 16,
    textAlign: 'center',
    marginTop: -1,
  },
  shareStatus: {
    backgroundColor: 'rgba(0, 255, 0, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 0, 0.3)',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  shareStatusText: {
    color: '#0f0',
    fontSize: 14,
    fontWeight: '600',
    flex: 1,
  },
  shareStatusSubtext: {
    color: '#0f0',
    fontSize: 12,
    flex: 1,
    marginTop: 4,
  },
  clearButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 2,
  },
  clearButtonText: {
    color: '#e8e8ea',
    fontSize: 12,
    fontWeight: '600',
  },
  // Grid Layout Styles
  gridContent: {
    paddingBottom: 100, // Add bottom padding to avoid tab bar overlap
  },
  row: {
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  gridCard: {
    width: cardWidth,
    backgroundColor: '#0f1013',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#202126',
    overflow: 'hidden',
    position: 'relative',
  },
  cardTouchable: {
    flex: 1,
    height: cardHeight,
  },
  thumbnailContainer: {
    position: 'relative',
    width: '100%',
    height: cardHeight,
    backgroundColor: '#000',
  },
  thumbnail: {
    width: '100%',
    height: '100%',
  },
  placeholderThumbnail: {
    backgroundColor: '#1a1b1f',
    justifyContent: 'center',
    alignItems: 'center',
  },
  placeholderText: {
    color: '#cfcfd4',
    fontSize: 18,
    fontWeight: '600',
  },
  playOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
  },
  playButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  playIcon: {
    color: '#000',
    fontSize: 18,
    marginLeft: 3, // Slight offset to center the triangle
  },
  badgeContainer: {
    position: 'absolute',
    top: 8,
    left: 8,
  },
  newBadge: {
    backgroundColor: 'rgba(0, 123, 255, 0.7)',
    color: '#fff',
    fontSize: 10,
    fontWeight: '700',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  platformTag: {
    position: 'absolute',
    bottom: 8,
    left: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  platformTagYouTube: {
    backgroundColor: 'rgba(204, 0, 0, 0.3)',
    borderColor: 'rgba(255, 0, 0, 0.2)',
  },
  platformTagTikTok: {
    backgroundColor: 'transparent',
    borderColor: 'rgba(0, 242, 234, 0.3)',
    overflow: 'hidden',
  },
  platformTagTikTokGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 6,
    overflow: 'hidden',
    flexDirection: 'column',
  },
  tiktokColorSection: {
    flex: 1,
    height: '100%',
  },
  tiktokColorSection1: {
    backgroundColor: 'rgba(0, 242, 234, 0.3)',
  },
  tiktokColorSection2: {
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  tiktokColorSection3: {
    backgroundColor: 'rgba(255, 0, 80, 0.3)',
  },
  platformTagInstagram: {
    backgroundColor: 'rgba(228, 64, 95, 0.3)',
    borderColor: 'rgba(255, 100, 130, 0.2)',
  },
  platformTagText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    textAlign: 'center',
    width: '100%',
    textShadowColor: '#000000',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 2,
  },
  cardInfo: {
    padding: 10,
  },
  cardTitle: {
    color: '#e8e8ea',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 4,
  },
  cardSubtitle: {
    color: '#b7b8bd',
    fontSize: 11,
    marginBottom: 4,
  },
  cardPlatform: {
    color: '#9a9ba1',
    fontSize: 10,
    textTransform: 'uppercase',
  },
  deleteButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 16,
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 68, 68, 0.3)',
    shadowColor: '#ff4444',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  deleteButtonText: {
    color: '#ff4444',
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 18,
  },
  noEmbedsText: {
    color: '#9a9ba1',
    fontSize: 16,
    textAlign: 'center',
    marginTop: 40,
  },
  loadingText: {
    color: '#e8e8ea',
    fontSize: 18,
    textAlign: 'center',
    marginTop: 40,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  errorText: {
    color: '#ff6b6b',
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 8,
  },
  errorSubtext: {
    color: '#aaa',
    fontSize: 14,
    textAlign: 'center',
  },
  backButton: {
    position: 'absolute',
    top: 44,
    left: 16,
    zIndex: 10,
    height: 40,
    width: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  backButtonText: {
    color: '#e8e8ea',
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 24,
  },
  // Filter Page Styles
  filterContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  filterHeader: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 40,
    paddingTop: 60,
    paddingBottom: 20,
    position: 'relative',
  },
  filterTitle: {
    color: '#e8e8ea',
    fontSize: 28,
    fontWeight: '700',
    textAlign: 'center',
  },
  filterBackButton: {
    position: 'absolute',
    left: 0,
    top: 60,
    height: 40,
    width: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  filterBackButtonText: {
    color: '#e8e8ea',
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 24,
  },
  filterSection: {
    marginBottom: 32,
  },
  filterSectionTitle: {
    color: '#e8e8ea',
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 20,
    paddingLeft: 4,
  },
  filterOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0f1013',
    borderRadius: 16,
    padding: 20,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#202126',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  filterOptionSelected: {
    backgroundColor: 'rgba(0, 123, 255, 0.08)',
    borderColor: 'rgba(0, 123, 255, 0.3)',
  },
  filterOptionIcon: {
    fontSize: 24,
    marginRight: 16,
    width: 32,
    textAlign: 'center',
  },
  filterOptionText: {
    color: '#e8e8ea',
    fontSize: 17,
    fontWeight: '500',
    flex: 1,
  },
  filterOptionTextSelected: {
    color: '#007bff',
    fontWeight: '600',
  },
  toggleSwitch: {
    width: 50,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#2a2a2a',
    borderWidth: 1,
    borderColor: '#404040',
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  toggleSwitchActive: {
    backgroundColor: '#007bff',
    borderColor: '#007bff',
  },
  toggleThumb: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  toggleThumbActive: {
    alignSelf: 'flex-end',
  },
});
