import { Dimensions, StyleSheet } from 'react-native';

// Get screen dimensions for grid layout
const { width: screenWidth } = Dimensions.get('window');
const cardWidth = (screenWidth - 60) / 2; // 2 columns with padding
const cardHeight = cardWidth * 1.77; // 9:16 aspect ratio

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0b0b0c',
  },
  webview: {
    flex: 1,
    backgroundColor: '#000',
  },
  menuContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  titleRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginBottom: 16,
    paddingTop: 60,
    paddingBottom: 8,
    position: 'relative',
  },
  title: {
    color: '#e8e8ea',
    fontSize: 28,
    fontWeight: '700',
    textAlign: 'center',
    flex: 1,
  },
  titleSpacer: {
    width: 44, // Same width as filter button to balance the layout
  },
  debugButton: {
    backgroundColor: 'rgba(255, 107, 107, 0.15)',
    borderRadius: 12,
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 107, 107, 0.4)',
    shadowColor: '#ff6b6b',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  rightButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  storageToggleButton: {
    backgroundColor: 'rgba(108, 117, 125, 0.15)',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: 'rgba(108, 117, 125, 0.4)',
  },
  storageToggleButtonActive: {
    backgroundColor: 'rgba(0, 123, 255, 0.15)',
    borderColor: 'rgba(0, 123, 255, 0.4)',
  },
  storageToggleText: {
    color: '#8E8E93',
    fontSize: 12,
    fontWeight: '500',
  },
  storageToggleTextActive: {
    color: '#007bff',
    fontWeight: '600',
  },
  storageIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginBottom: 12,
    alignSelf: 'flex-start',
  },
  storageDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 8,
  },
  storageIndicatorText: {
    color: '#e8e8ea',
    fontSize: 12,
    fontWeight: '500',
  },
  filterButton: {
    backgroundColor: 'rgba(0, 123, 255, 0.15)',
    borderRadius: 12,
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0, 123, 255, 0.4)',
    shadowColor: '#007bff',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  filterButtonText: {
    color: '#007bff',
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 16,
    textAlign: 'center',
    marginTop: -1,
  },
  shareStatus: {
    backgroundColor: 'rgba(0, 255, 0, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(0, 255, 0, 0.3)',
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  shareStatusText: {
    color: '#0f0',
    fontSize: 14,
    fontWeight: '600',
    flex: 1,
  },
  shareStatusSubtext: {
    color: '#0f0',
    fontSize: 12,
    flex: 1,
    marginTop: 4,
  },
  clearButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 2,
  },
  clearButtonText: {
    color: '#e8e8ea',
    fontSize: 12,
    fontWeight: '600',
  },
  // Grid Layout Styles
  gridContent: {
    paddingBottom: 100, // Add bottom padding to avoid tab bar overlap
  },
  row: {
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  gridCard: {
    width: cardWidth,
    backgroundColor: '#0f1013',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#202126',
    overflow: 'hidden',
    position: 'relative',
  },
  cardTouchable: {
    flex: 1,
    height: cardHeight,
  },
  thumbnailContainer: {
    position: 'relative',
    width: '100%',
    height: cardHeight,
    backgroundColor: '#000',
  },
  thumbnail: {
    width: '100%',
    height: '100%',
  },
  placeholderThumbnail: {
    backgroundColor: '#1a1b1f',
    justifyContent: 'center',
    alignItems: 'center',
  },
  placeholderText: {
    color: '#cfcfd4',
    fontSize: 18,
    fontWeight: '600',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  playOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
  },
  playButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  playIcon: {
    color: '#000',
    fontSize: 18,
    marginLeft: 3, // Slight offset to center the triangle
  },
  badgeContainer: {
    position: 'absolute',
    top: 8,
    left: 8,
  },
  newBadge: {
    backgroundColor: 'rgba(0, 123, 255, 0.7)',
    color: '#fff',
    fontSize: 10,
    fontWeight: '700',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  platformTag: {
    position: 'absolute',
    bottom: 8,
    left: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
  },
  platformTagYouTube: {
    backgroundColor: 'rgba(204, 0, 0, 0.4)',
    borderColor: 'rgba(255, 0, 0, 0.4)',
  },
  platformTagTikTok: {
    backgroundColor: 'transparent',
    borderColor: 'rgba(0, 242, 234, 0.4)',
    overflow: 'hidden',
  },
  platformTagTikTokGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 6,
    overflow: 'hidden',
    flexDirection: 'column',
  },
  tiktokColorSection: {
    flex: 1,
    height: '100%',
  },
  tiktokColorSection1: {
    backgroundColor: 'rgba(0, 242, 234, 0.4)',
  },
  tiktokColorSection2: {
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
  },
  tiktokColorSection3: {
    backgroundColor: 'rgba(255, 0, 80, 0.4)',
  },
  platformTagInstagram: {
    backgroundColor: 'transparent',
    borderColor: 'rgba(131, 58, 180, 1)',
    overflow: 'hidden',
  },
  platformTagInstagramGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 6,
    overflow: 'hidden',
    flexDirection: 'column',
  },
  instagramColorSection: {
    flex: 1,
    height: '100%',
  },
  instagramColorSection1: {
    backgroundColor: 'rgba(131, 58, 180, 0.4)',
  },
  instagramColorSection2: {
    backgroundColor: 'rgba(225, 48, 108, 0.4)',
  },
  instagramColorSection3: {
    backgroundColor: 'rgba(252, 175, 69, 0.4)',
  },
  platformTagText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    textAlign: 'center',
    width: '100%',
    textShadowColor: '#000000',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 2,
  },
  cardInfo: {
    padding: 10,
  },
  cardTitle: {
    color: '#e8e8ea',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 4,
  },
  cardSubtitle: {
    color: '#b7b8bd',
    fontSize: 11,
    marginBottom: 4,
  },
  cardPlatform: {
    color: '#9a9ba1',
    fontSize: 10,
    textTransform: 'uppercase',
  },
  deleteButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 16,
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 68, 68, 0.3)',
    shadowColor: '#ff4444',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  deleteButtonText: {
    color: '#ff4444',
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 18,
  },
  noEmbedsText: {
    color: '#9a9ba1',
    fontSize: 16,
    textAlign: 'center',
    marginTop: 40,
  },
  loadingText: {
    color: '#e8e8ea',
    fontSize: 18,
    textAlign: 'center',
    marginTop: 40,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  errorText: {
    color: '#ff6b6b',
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 8,
  },
  errorSubtext: {
    color: '#aaa',
    fontSize: 14,
    textAlign: 'center',
  },
  backButton: {
    position: 'absolute',
    top: 44,
    left: 16,
    zIndex: 10,
    height: 40,
    width: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  backButtonText: {
    color: '#e8e8ea',
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 24,
  },
  // Filter Page Styles
  filterContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  filterContent: {
    flex: 1,
  },
  filterScrollContent: {
    paddingBottom: 60, // Add bottom padding to avoid tab bar overlap
  },
  filterHeader: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 40,
    paddingTop: 60,
    paddingBottom: 20,
    position: 'relative',
  },
  filterTitle: {
    color: '#e8e8ea',
    fontSize: 28,
    fontWeight: '700',
    textAlign: 'center',
  },
  filterBackButton: {
    position: 'absolute',
    left: 0,
    top: 60,
    height: 40,
    width: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  filterBackButtonText: {
    color: '#e8e8ea',
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 24,
  },
  filterSection: {
    marginBottom: 32,
  },
  filterSectionTitle: {
    color: '#e8e8ea',
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 20,
    paddingLeft: 4,
  },
  filterOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0f1013',
    borderRadius: 16,
    padding: 20,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#202126',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  filterOptionSelected: {
    backgroundColor: 'rgba(0, 123, 255, 0.08)',
    borderColor: 'rgba(0, 123, 255, 0.3)',
  },
  filterOptionIcon: {
    fontSize: 24,
    marginRight: 16,
    width: 32,
    textAlign: 'center',
  },
  filterOptionText: {
    color: '#e8e8ea',
    fontSize: 17,
    fontWeight: '500',
    flex: 1,
  },
  filterOptionTextSelected: {
    color: '#007bff',
    fontWeight: '600',
  },
  toggleSwitch: {
    width: 50,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#2a2a2a',
    borderWidth: 1,
    borderColor: '#404040',
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  toggleSwitchActive: {
    backgroundColor: '#007bff',
    borderColor: '#007bff',
  },
  toggleThumb: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  toggleThumbActive: {
    alignSelf: 'flex-end',
  },
  
  // Edit button
  editButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    borderRadius: 16,
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  editButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  
  // Modal styles
  modalContainer: {
    flex: 1,
    backgroundColor: '#0b0b0c',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    position: 'relative',
  },
  modalCloseButton: {
    padding: 8,
  },
  modalCloseButtonText: {
    color: '#e8e8ea',
    fontSize: 20,
    fontWeight: '600',
  },
  modalTitle: {
    color: '#e8e8ea',
    fontSize: 18,
    fontWeight: '600',
    flex: 1,
    textAlign: 'center',
    marginHorizontal: 20,
  },
  modalSaveButton: {
    backgroundColor: '#007bff',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  modalSaveButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  modalHeaderSpacer: {
    width: 40,
  },
  modalHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  modalDeleteButton: {
    backgroundColor: 'rgba(255, 59, 48, 0.15)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 59, 48, 0.4)',
  },
  modalDeleteButtonText: {
    color: '#FF3B30',
    fontSize: 16,
    fontWeight: '600',
  },
  modalContent: {
    flex: 1,
  },
  
  // Clip info styles
  clipInfo: {
    paddingVertical: 24,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
  },
  clipTitle: {
    color: '#e8e8ea',
    fontSize: 22,
    fontWeight: '700',
    marginBottom: 12,
    lineHeight: 28,
  },
  clipSubtitle: {
    color: '#999',
    fontSize: 16,
    marginBottom: 12,
    lineHeight: 22,
  },
  clipUrl: {
    color: '#666',
    fontSize: 14,
    fontFamily: 'monospace',
  },
  
  // Categories section
  categoriesSection: {
    paddingVertical: 24,
    paddingHorizontal: 20,
  },
  categoriesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  categoriesTitle: {
    color: '#e8e8ea',
    fontSize: 20,
    fontWeight: '700',
  },
  addToCategoriesButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 123, 255, 0.15)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 123, 255, 0.4)',
    gap: 6,
  },
  addToCategoriesButtonText: {
    color: '#007bff',
    fontSize: 14,
    fontWeight: '600',
  },
  selectedCategoriesList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  categoryBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    gap: 6,
  },
  categoryBadgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },
  categoryBadgeRemove: {
    padding: 2,
  },
  categoryDropdown: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    padding: 8,
    marginTop: 8,
  },
  categoryDropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: 8,
  },
  categoryDropdownItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  categoryDropdownItemText: {
    color: '#e8e8ea',
    fontSize: 16,
    fontWeight: '500',
    marginLeft: 8,
  },
  manageCategoriesButton: {
    backgroundColor: 'rgba(0, 123, 255, 0.15)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 123, 255, 0.4)',
  },
  manageCategoriesButtonText: {
    color: '#007bff',
    fontSize: 14,
    fontWeight: '600',
  },
  categoriesList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  categoryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  categoryChipSelected: {
    backgroundColor: 'rgba(0, 123, 255, 0.2)',
    borderColor: '#007bff',
  },
  categoryColorDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 8,
  },
  categoryChipText: {
    color: '#e8e8ea',
    fontSize: 14,
    fontWeight: '500',
  },
  categoryChipTextSelected: {
    color: '#007bff',
  },
  
  // Category manager styles
  addCategorySection: {
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  addCategoryTitle: {
    color: '#e8e8ea',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 16,
  },
  addCategoryInput: {
    flexDirection: 'row',
    gap: 12,
  },
  categoryInput: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    color: '#e8e8ea',
    fontSize: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  addCategoryButton: {
    backgroundColor: '#007bff',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addCategoryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  existingCategoriesSection: {
    paddingVertical: 20,
  },
  existingCategoriesTitle: {
    color: '#e8e8ea',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 16,
  },
  categoryItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 8,
    marginBottom: 8,
  },
  categoryItemInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  categoryItemName: {
    color: '#e8e8ea',
    fontSize: 16,
    fontWeight: '500',
    marginLeft: 12,
  },
  deleteCategoryButton: {
    padding: 8,
  },
  deleteCategoryButtonText: {
    fontSize: 16,
  },
  
  filterButtonActive: {
    backgroundColor: 'rgba(0, 123, 255, 0.3)',
    borderColor: 'rgba(0, 123, 255, 0.6)',
  },
  
  // Category filter modal
  categoryFilterOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  categoryFilterOptionSelected: {
    backgroundColor: 'rgba(0, 123, 255, 0.2)',
    borderColor: '#007bff',
  },
  categoryFilterOptionInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  categoryFilterOptionText: {
    color: '#e8e8ea',
    fontSize: 16,
    fontWeight: '500',
    marginLeft: 12,
  },
  categoryFilterOptionTextSelected: {
    color: '#007bff',
  },
  categoryCount: {
    color: '#999',
    fontSize: 14,
    fontWeight: '500',
  },
  
  // Active filter indicator
  activeFilterIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 123, 255, 0.1)',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 20,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: 'rgba(0, 123, 255, 0.3)',
    shadowColor: '#007bff',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  activeFilterText: {
    color: '#007bff',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 10,
    flex: 1,
  },
  clearFilterButton: {
    marginLeft: 12,
    padding: 8,
    borderRadius: 12,
    backgroundColor: 'rgba(0, 123, 255, 0.2)',
  },
  clearFilterButtonText: {
    color: '#007bff',
    fontSize: 12,
    fontWeight: '600',
  },
});
